server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loans?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: "loans"
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
test:
  config:
    age: 13
    name: đức anh
    mylist:
      - item11
      - item22
      - item33
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
info:
  app:
    name: "loans"
    description: "loans"
    version: "1.0.0"
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
